// Copy contract ABIs from contracts/out into packages/shared/src/abi.ts.
// Run after `forge build`: node scripts/gen-abi.mjs
import { readFileSync, writeFileSync } from "node:fs";

const names = ["ObeliskVault", "ObeliskVaultFactory", "AgentRegistry", "MockVerifier", "MockERC20", "MockSwapRouter"];
let out = "// AUTO-GENERATED by scripts/gen-abi.mjs. Do not edit by hand.\n\n";
for (const n of names) {
  const { abi } = JSON.parse(readFileSync(`contracts/out/${n}.sol/${n}.json`, "utf8"));
  const id = n[0].toLowerCase() + n.slice(1) + "Abi";
  out += `export const ${id} = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}
writeFileSync("packages/shared/src/abi.ts", out);
console.log("wrote packages/shared/src/abi.ts");
